
name: Guestbook CI/CD Production
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "diagrams/**"

  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "diagrams/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v -o guestbook-prod -ldflags="-s -w" ./
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: guestbook-prod
          path: guestbook-prod
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: guestbook-prod
          path: ./
      - name: Set executable permissions
        run: chmod +x guestbook-prod
      - name: Deploy to server-${{ secrets.SERVER_HOST }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH_PROD: ${{ secrets.SERVER_PATH_PROD }}
          SERVICE_NAME_PROD: ${{ secrets.SERVICE_NAME_PROD }}
        run: >
          echo "$SSH_PRIVATE_KEY" > private_key

          chmod 600 private_key         

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo systemctl stop $SERVICE_NAME_PROD"
          
          scp -o StrictHostKeyChecking=no -i private_key guestbook-prod $SERVER_USER@$SERVER_HOST:$SERVER_PATH_PROD

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo systemctl start $SERVICE_NAME_PROD"

          rm -f private_key

          