
name: Guestbook CI/CD Staging
on:
  workflow_dispatch: {}
  push:
    branches:
      - staging
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "diagram/**"
      
  pull_request:
    branches:
      - staging
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "diagram/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v -o guestbook-stag -ldflags="-s -w" ./
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: guestbook-stag
          path: guestbook-stag
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: guestbook-stag
          path: ./
      - name: Set executable permissions
        run: chmod +x guestbook-stag
      - name: Deploy to server-${{ secrets.SERVER_HOST }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH_STAG: ${{ secrets.SERVER_PATH_STAG }}
          SERVICE_NAME_STAG: ${{ secrets.SERVICE_NAME_STAG }}
        run: >
          echo "$SSH_PRIVATE_KEY" > private_key

          chmod 600 private_key         

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo systemctl stop $SERVICE_NAME_STAG"
          
          scp -o StrictHostKeyChecking=no -i private_key guestbook-stag $SERVER_USER@$SERVER_HOST:$SERVER_PATH_STAG

          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_HOST "sudo systemctl start $SERVICE_NAME_STAG"

          rm -f private_key

          